### ISSUE TITLE
How about DynamoDB?

### ISSUE THREAD

**Issue by scytacki** [silinternational/ecs-agent-monitor#6]
Did you consider using DynamoDB instead of Firebase.  I love Firebase, but in this case DynamoDB might be better.  Or perhaps you tried DynamoDB and found a problem.

If it used DynamoDB the whole stack of resources for this monitor could be put into a cloudformation template, and then it would be more simple to deploy.

**Comment by fillup** [comment]
Great question. I believe we tried Redis via Elasticache but found the endpoint had to be in a specific  VPC and then the lambda needed to be as well and then it was more difficult to monitor multiple ECS clusters that were in multiple VPCs. I'm open to DynamoDB though if it can easily be used by a lambda not in the same VPC as it.

**Comment by jleloup** [comment]
Regarding Lamba use cases with DynamoDB : using DynamoDB should not be an issue in this situation.
I'm currently a Lambda with a similar use case (doing AWS endpoint calls & store actions/events in a DynamoDB table) without attaching it to any VPC. As scytacki mentioned, this is pretty cool to have all of those object in the same CloudFormation template.

I'm considering implementing this DynamoDB setup based on your code. If anybody is already working on this, I would like to open a Pull Request when this will be ready.
So for this : do you want to keep the capability to use Firebase ? Or fully replacing it by DynamoDB is OK ?

Also I plan to add a custom metric to get in Cloudwatch some graph & alerting based on the number of time when an ECS instance was replaced due to agent failure. Is it ok to provide this feature in the same PR ?

**Comment by fillup** [comment]
@jleloup that sounds good, please do. I'm not tied to Firebase, I guess I just didn't know how to use DynamoDB right. I'd be happy to accept a PR that changes this over to use DynamoDB instead of Firebase.

**Comment by Normo** [comment]
@scytacki, @fillup 
I've opened pull request #7 to switch from firebase to DynamoDB.

**Comment by devon-sil** [comment]
We're archiving this repo.  Closing this issue.
